[project]
name = "leadr-sdk-godot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gdtoolkit==4.3.1",
    "pre-commit>=4.5.1",
]
